name: Unit Tests
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Copy application.properties.sample to application.properties
      run: cp src/main/resources/application.properties.sample src/main/resources/application.properties
    - name: Build with Maven
      run: mvn -B test --file pom.xml
      
